[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "market-creator"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
repository = "https://github.com/valory-xyz/dev-template"
keywords = [ "autonomy", "autonomous", "autonolas", "service", "multi", "agent",]
classifiers = [ "Environment :: Console", "Environment :: Web Environment", "Development Status :: 2 - Pre-Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Natural Language :: English", "Operating System :: MacOS", "Operating System :: Microsoft", "Operating System :: Unix", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Topic :: Communications", "Topic :: Internet", "Topic :: Scientific/Engineering", "Topic :: Software Development", "Topic :: System",]
[[tool.poetry.packages]]
include = "packages"

[tool.poetry.dependencies]
python = "<3.12,>=3.10"
open-autonomy = "==0.21.8"
toml = "==0.10.2"
hypothesis = "==6.21.6"
grpcio = "==1.53.0"
typing-extensions = "4.12.2"
aiohttp = "<4.0.0,>=3.8.5"
asn1crypto = "<1.5.0,>=1.4.0"
open-aea-ledger-ethereum = "==2.0.8"
openai = "1.93.0"
protobuf = "<4.25.0,>=4.21.6"
open-aea-test-autonomy = "==0.21.8"
ipfshttpclient = "==0.8.0a2"
open-aea-cli-ipfs = "==2.0.8"
requests = "<2.32.5,>=2.28.1"
pytest = "==7.4.4"
pytest-asyncio = "*"
ecdsa = ">=0.15"
open-aea-ledger-cosmos = "==2.0.8"
certifi = "*"
multidict = "*"
py-eth-sig-utils = "*"
web3 = "<8,>=7.0.0"
eth_typing = "*"
pytz = "==2022.2.1"
typing_extensions = "<=4.13.2,>=3.10.0.2"
hexbytes = "*"
packaging = "*"
tomte = {version = "==0.4.0", extras = ["cli", "tests"]}
openapi-core = "==0.15.0"
openapi-spec-validator = "<0.5.0,>=0.4.0"
flask-cors = "^5.0.0"
gql = "^3.5.0"
pydantic = "==2.11.9"
tiktoken = "^0.9.0"
eth-utils = "==5.3.0"
